apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-basic-1777098459744
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/quay_xjiang/test-image:4349d2ac074f473f0444a320b9c3a83606f81227
        name: container-image  
